sudo: false
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
language: c
compiler:
  - gcc
  - clang
before_script:
  - redis-server --port 6379 &
  - redis-server --port 6380 --requirepass 'secret' &
script:
  - rake test
